export const dataConstants = {
	SET_DATA_REQUEST: "SET_DATA_REQUEST",
	SET_DATA_SUCCESS: "SET_DATA_SUCCESS",
	SET_DATA_FAILURE: "SEt_DATA_FAILURE",

	FIND_BY_ID_DATA_REQUEST: "FIND_BY_ID_DATA_REQUEST",
	FIND_BY_ID_DATA_SUCCESS: "FIND_BY_ID_DATA_SUCCESS",
	FIND_BY_ID_DATA_FAILURE: "FIND_BY_ID_DATA_FAILURE",

	EDIT_DATA_IMAGE_DESELECTED: "EDIT_DATA_IMAGE_DESELECTED",
	EDIT_DATA_IMAGE_SELECTED: "EDIT_DATA_IMAGE_SELECTED",
	EDIT_DATA_MODAL_HIDE_ERROR: "EDIT_DATA_MODAL_HIDE_ERROR",

	EDIT_DATA_REQUEST: "EDIT_DATA_REQUEST",
	EDIT_DATA_SUCCESS: "EDIT_DATA_SUCCESS",
	EDIT_DATA_FAILURE: "EDIT_DATA_FAILURE",



};
