export const fileConstants = {
	
	FILE_SUBMIT_REQUEST: "FILE_SUBMIT_REQUEST",
	FILE_SUBMIT_FAILURE: "FILE_SUBMIT_FAILURE",
	FILE_SUBMIT_SUCCESS: "FILE_SUBMIT_SUCCESS",

	SET_FILES_REQUEST: "SET_FILES_REQUEST",
	SET_FILES_SUCCESS: "SET_FILES_SUCCESS",
	SET_FILES_FAILURE: "SET_FILES_FAILURE",

	SET_FILE_REMOVE_REQUEST: "SET_FILE_REMOVE_REQUEST",
	SET_FILE_REMOVE_SUCCESS: "SET_FILE_REMOVE_SUCCESS",
	SET_FILE_REMOVE_FAILURE: "SET_FILE_REMOVE_FAILURE",

	HIDE_MODAL_INFO: "HIDE_MODAL_INFO",
};
