export const modalConstants = {
	HIDE_CREATE_DATA_MODAL: "HIDE_CREATE_PRODUCT_MODAL",
	SHOW_CREATE_DATA_MODAL: "SHOW_CREATE_PRODUCT_MODAL",

	HIDE_EDIT_DATA_MODAL: "HIDE_EDIT_DATA_MODAL",
	SHOW_EDIT_DATA_MODAL: "SHOW_EDIT_DATA_MODAL",

	HIDE_UPLOAD_FILES_MODAL: "HIDE_UPLOAD_FILES_MODAL",
	SHOW_UPLOAD_FILES_MODAL: "SHOW_UPLOAD_FILES_MODAL",

	HIDE_RESERVE_TRANSFER_MODAL: "HIDE_RESERVE_TRANSFER_MODAL",
	SHOW_RESERVE_TRANSFER_MODAL: "SHOW_RESERVE_TRANSFER_MODAL",

    FILE_UPLOAD_FILE_SELECTED: "FILE_UPLOAD_FILE_SELECTED",
	FILE_UPLOAD_MODAL_HIDE_ERROR: "FILE_UPLOAD_MODAL_HIDE_ERROR",

};
