export const transferInfoConstants = {
	
    SET_TRANSFER_INFO_REQUEST: "SET_TRANSFER_INFO_REQUEST",
	SET_TRANSFER_INFO_SUCCESS: "SET_TRANSFER_INFO_SUCCESS",
	SET_TRANSFER_INFO_FAILURE: "SET_TRANSFER_INFO_FAILURE",
};