export const travelInfoConstants = {
	
    SET_TRAVEL_INFO_REQUEST: "SET_TRAVEL_INFO_REQUEST",
	SET_TRAVEL_INFO_SUCCESS: "SET_TRAVEL_INFO_SUCCESS",
	SET_TRAVEL_INFO_FAILURE: "SET_TRAVEL_INFO_FAILURE",
};
